export const DEPLOY_CONTRACT_SUCCESSFUL = "DEPLOY_CONTRACT_SUCCESSFUL";
export const DEPLOY_CONTRACT_FAILED = "DEPLOY_CONTRACT_FAILED";
export const DEPLOY_CONTRACT_LOADING = "DEPLOY_CONTRACT_LOADING";

export const DEPLOYMENT_VALUES_LOADING = "DEPLOYMENT_VALUES_LOADING";
export const DEPLOYMENT_VALUES_ERROR = "DEPLOYMENT_VALUES_ERROR";
export const DEPLOYMENT_VALUES_SUCCESS = "DEPLOYMENT_VALUES_SUCCESS";

export const ADD_REWARD_SUCCESSFULL = "ADD_REWARD_SUCCESSFULL";
export const ADD_REWARD_FAILED = "ADD_REWARD_FAILED";
export const ADD_REWARD_REQUEST = "ADD_REWARD_REQUEST";

export const ADD_STAKE_SUCCESSFULL = "ADD_STAKE_SUCCESSFULL";
export const ADD_STAKE_FAILED = "ADD_STAKE_FAILED";
export const ADD_STAKE_REQUEST = "ADD_STAKE_REQUEST";
export const UPDATE_STAKE_VARIABLES = "UPDATE_STAKE_VARIABLES";
export const APPROVE_STAKE_SUCCESSFULL = "APPROVE_STAKE_SUCCESSFULL";
export const APPROVE_STAKE_FAILED = "APPROVE_STAKE_FAILED";

export const WITHDRAW_SUCCESSFULL = "WITHDRAW_SUCCESSFULL";
export const WITHDRAW_FAILED = "WITHDRAW_FAILED";
export const WITHDRAW_REQUEST = "WITHDRAW_REQUEST";
export const SET_WITHDRAW_TO_DEFAULT_STATE = "SET_WITHDRAW_TO_DEFAULT_STATE";
