export const DEPLOY_CONTRACT_SUCCESSFUL = "DEPLOY_CONTRACT_SUCCESSFUL";
export const DEPLOY_CONTRACT_FAILED = "DEPLOY_CONTRACT_FAILED";
export const DEPLOY_CONTRACT_LOADING = "DEPLOY_CONTRACT_LOADING";

export const DEPLOYMENT_VALUES_LOADING = "DEPLOYMENT_VALUES_LOADING";
export const DEPLOYMENT_VALUES_ERROR = "DEPLOYMENT_VALUES_ERROR";
export const DEPLOYMENT_VALUES_SUCCESS = "DEPLOYMENT_VALUES_SUCCESS";
